config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcomes#index"
  resources :books do
   resources :madlibs
  end
  resource :session, only: [:create, :destroy, :show]
  resources :users
  resources :wordforms
  resources :mailers, only: [:create]

  get '/instructions' => 'statics#instructions'
  get '/storyinstructions' => 'statics#storyinstructions'
  get '/exclusive' => 'statics#exclusiveexplanation'
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/facebook/callback', to: 'users#create'
  get 'auth/failure', to: redirect("/")
end

app/models/madlib.rb
class Madlib < ActiveRecord::Base
  belongs_to :book
  has_one :wordform

  def populate_story(story)
    misswords_array = self.split_up_misswords
    punctuation = [".", "?", "!"]
    story.each_with_index do |word,idx|
      if word[0] == "_"
        if punctuation.include?(word[-1])
          story[idx] = "_" + misswords_array.shift.gsub(/[\[\]\"]/, "")+ "_" + word[-1]
        else
          story[idx] = "_" + misswords_array.shift.gsub(/[\[\]\"]/, "") + "_"
        end
      end
    end
    story.join(" ")
  end

  def array_story
     self.story.split()
  end

  def split_up_misswords
    self.wordform.misswords.split(", ")
  end

  def count_missing_words
    count = 0
    self.story.split.each do |word|
      if word[0] == "_"
        count+=1
      end
    end
    count
  end

  def check_user_story
    punctuation = [".", "?", "!"]
    count = 0
    user_story = self.array_story
    user_story.each do |word|
      if (word[0] == "_")
        if (punctuation.include?(word[-1]) && word[-2] == "_") ||
          (word[-1] == "_")
          count+=1
        end
      end
    end
    if count == 0
      return false
    else
      return count
    end
  end

  def self.create_wordform(madlib)
    @wordform = Wordform.new
    @wordform.madlib_id = madlib.id
    @wordform.words = @wordform.make_user_form(madlib)
    @wordform.save!
    madlib.wordform = @wordform
    madlib.save!
    return [madlib, @wordform]
  end

end

app/controllers/madlibs_controller.rb
class MadlibsController < ApplicationController

  def index
    @madlibs = Madlib.where("book_id" => params[:book_id])
    @book = Book.find(params[:book_id])
    render 'index'
  end

  def show
    @madlib = Madlib.find(params[:id])

    if (!@madlib.wordform.misswords.nil?)
      story = @madlib.array_story
      @madlib.story = @madlib.populate_story(story)
    end
    render 'show'
  end

  def new
    @book = Book.find(params[:book_id])
    @madlib = Madlib.new
  end

  def create
    if params[:reset]
      @madlib = Madlib.find(params[:madlib][:id])
      title = params[:madlib][:title]
      story = params[:madlib][:story]
      if title.empty? || story.empty? || title.nil? || story.nil?
        redirect_to new_book_madlib_path, :flash => { :error => "Make sure both title and story are filled in." }
      else
        @madlib.title = title
        @madlib.story = story
        @madlib.save!
        madlib_and_form = Madlib.create_wordform(@madlib)
        @wordform = madlib_and_form[1]
        @madlib = madlib_and_form[0]
        redirect_to wordform_path(@wordform.id, @madlib)
      end
    else
      title = params[:madlib][:title]
      story = params[:madlib][:story]
      if title.empty? || story.empty? || title.nil? || story.nil?
        redirect_to new_book_madlib_path, :flash => { :error => "Make sure both title and story are filled in." }
      else
        @madlib = Madlib.new(madlib_params)
        if !@madlib.check_user_story
          redirect_to new_book_madlib_path, :flash => { :error => "It doesn't look like you left out any words.
            Make sure each word you want to leave out begins and ends with a _ ." }
        else
          @madlib.book_id = params[:madlib][:book_id]
          @madlib.save!
          madlib_and_form = Madlib.create_wordform(@madlib)
          @wordform = madlib_and_form[1]
          @madlib = madlib_and_form[0]
          redirect_to wordform_path(@wordform.id, @madlib)
        end
      end
    end
  end

  def update
    if params[:commit]
      @madlib = Madlib.find(params[:book_id])
      story = @madlib.array_story
      @madlib.story = @madlib.populate_story(story);
      render 'show'
    end
  end

  def edit
    @madlib = Madlib.find(params[:id])
    @book = Book.find(params[:book_id])
    if params[:reset]
      @madlib.wordform.misswords = nil
      @madlib.wordform.save!
      @madlib.misswords = nil
      @madlib.save!
      redirect_to wordform_path(@madlib.wordform.id)
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    @madlibs = Madlib.where("book_id" => params[:book_id])
    @madlib = Madlib.find(params[:id])
    @madlib.destroy
    render 'index'
  end

  def madlib_params
    params.require(:madlib).permit(:title, :story, :book_id)
  end

end

app/views/madlibs/edit.html.erb
<div class="text-center madlibs-form container-fluid">
  <%= link_to "Cancel", book_madlibs_path(@madlib.book_id), :class => "log-in-inputs log-in-button delete-account" %>
<div class="madlibs-edit-wrapper">
  <div class="row">
    <div class="col-sm-12 col-md-12">
      <div class="madlibs-form-wrapper">
        <form class="" action="/books/<%= @book.id %>/madlibs" method="post">
          <input
             name="authenticity_token"
             type="hidden"
             value="<%= form_authenticity_token %>">
          <input name="reset" type="hidden" value="true">
          <input name="madlib[id]" type="hidden" value="<%= @madlib.id %>">
          <input type="hidden" name="madlib[book_id]" value="<%= @book.id %>">
          <label for="title">Title:</label><br>
          <input type="text" name="madlib[title]" value="<%= @madlib.title %>"><br />
          <label for="">Story:</label><br />
          <textarea type="text" name="madlib[story]" value="" rows="12" cols="50"><%= @madlib.story %></textarea><br>
          <input type="submit" name="" value="Edit Story">
        </form>
      </div>
    </div>
  </div>
</div>

</div>

app/views/madlibs/index.html.erb
<h1 id="h1-overrides" class="home-page">
  <%=link_to @book.title, books_path %>
</h1>
<div class="container-fluid">


  <% if !current_user.nil? %>
    <% if current_user[:id] == @book.user_id %>
    <div class="row text-center madlibs-list-title-header">
      <div class="col-sm-4">
        <%= button_to "Write a story!", new_book_madlib_path, :method => :get, :class=>"madlibs-list-title-button get-writing" %>
      </div>
      <% if @book.exclusive == 1%>
      <div class="col-sm-4">
        <%= button_to "Make this book Public!", book_path(@book.id), :method => :patch, params: { exclusive: :false }, :class=>"madlibs-list-title-button make-exclusive" %>
      </div>
      <% else %>
      <div class="col-sm-4">
        <%= button_to "Make this book Private!", book_path(@book.id), :method => :patch, params: { exclusive: :true }, :class=>"madlibs-list-title-button make-exclusive" %>
      </div>
      <% end %>
      <div class="col-sm-4">
          <%= button_to "Delete this Book", @book, :method => :get, :class=>"madlibs-list-title-button get-deleting"  %>
      </div>
      <div class="col-sm-12 text-center explain-books">
          <p class="dropdown-toggle dropdown-explain" data-toggle="dropdown" >What does this mean?</p>
            <ul class="dropdown-menu" id="center-ul">
              <div class="col-sm-12 text-center">
                <li>When you make a book public that means other users<br>
                  can see it and play your stories.<br>
                  Don't worry, you will be the only person who can edit or<br>
                  delete your book and stories.<br>
                  You can also make it a private book again anytime.
                </li>
              </div>
            </ul>

      </div>
    </div>
    <% end %>
  <% end %>
<div class="madlibs-list-container">
  <div class="row madlibs-list">
    <% if @madlibs.empty? %>
    <div class="row text-center">
      <div class="col-sm-12">
        <h2>There are no stories for this book yet!</h2>
      </div>
      <div class="col-sm-12">
        <h2>Write one now!</h2>
      </div>
    </div>



    <% end %>
    <% @madlibs.each do |ml| %>
      <div class="col-sm-3 text-center madlibs-list-wrapper">
        <% if ml.wordform.misswords.nil? %>
          <%= link_to ml.title, wordform_path(ml.wordform.id), {:class=> "madlibs-list-title"} %>
        <% else %>
          <%= link_to ml.title, book_madlib_path(@book, ml.id), {:class=> "madlibs-list-title"} %>
        <% end %>
        <% if (current_user && current_user[:id] == @book.user_id) %>
        <div class="row text-center">
          <div class="col-sm-12">
              <%= link_to "Edit", edit_book_madlib_path(@book, ml.id), {:class=> "madlibs-list-edit"}%>
          </div>
        </div>
        <div class="row text-center">
          <div class="col-sm-12">
              <%= link_to "Delete", book_madlib_path(@book, ml.id),
              :method => :delete,
              data: { confirm: "Are you sure? This cannot be undone"},
              :class => "madlibs-list-delete" %>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/madlibs/new.html.erb
<div class="text-center madlibs-header container-fluid">
  <div class="row">
    <div class="col-sm-12 h3-fun">
      <h3 class="">Create your own Madlibs!</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <p>for the book:</p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h1>"<%= link_to @book.title, book_madlibs_path(@book.id) %>"</h1>
    </div>
  </div>
</div>

<div class="text-center madlibs-form container-fluid">
  <div class=" create-madlib-container">
<div class="row big-background">
  <% if flash[:error]%>
    <p class="form-errors"><%= flash[:error] %></p>
  <% end %>
  <div class="col-sm-4 col-md-3">
    <div class="instructions-wrapper">
      <p class="first-child">Remember to leave out some words!</p>
      <p>Simply input the words you want to leave out like this:</p>
      <div class="example">
        <p>Adjective: _adj_</p>
        <p>Noun: _noun_</p>
        <p>Verb: _verb_</p>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-md-6">
    <div class="madlibs-form-wrapper">
      <form class="" action="/books/<%= @book.id %>/madlibs" method="post">
        <input
           name="authenticity_token"
           type="hidden"
           value="<%= form_authenticity_token %>">
           <input type="hidden" name="madlib[book_id]" value="<%= @book.id %>">
        <label for="title">Title:</label><br>
        <input type="text" name="madlib[title]" value=""><br />
        <label for="">Story:</label><br />
        <textarea type="text" name="madlib[story]" value="" rows="12" cols="50"></textarea><br>
        <input type="submit" name="" value="Create Madlib">
      </form>
    </div>
  </div>
  <div class="col-sm-4 col-md-3">
    <div class="instructions-wrapper wrapper-adjustments">
      <p>Example Story:</p>
      <div class="example">
        <p>Magda likes to _verb_.</p>
        <p>She is very _adj_!</p>
        <p>Does she know where the _noun_ is?</p>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/madlibs/show.html.erb
<div class="show-madlibs-main-container">

<div class="container-fluid  text-center">
  <div class="row show-madlibs-header">
    <div class="col-sm-12">
      <h1><%= @madlib.title %></h1>
      <h4>from the book:</h4>
      <h3><%= link_to @madlib.book.title, book_madlibs_path(@madlib.book_id) %></h3>
    </div>
  </div>

<div class="show-madlibs-container">
  <div class="row">
    <div class="col-sm-12">
      <% @madlib.story.split.each do |word| %>
        <% punctuation=[".", "!", "?"] %>
        <% if word[0] == "_" %>
          <% if punctuation.include?(word[-1])%>
            <span class="user-word"><%= word[0..-2] %></span><span><%= word[-1] %></span>
          <% else %>
            <span class="user-word"><%= word[0..-1] %></span>
            <% end %>
        <% else %>
          <span><%= word %></span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
    <div class="col-sm-12 reset-column">
      <%= link_to "Reset", edit_book_madlib_path(@madlib.book_id, @madlib.id, :reset => "true"),
      :class => "reset-madlib" %>
  </div>
</div>

</div>
</div>