config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcomes#index"
  resources :books do
   resources :madlibs
  end
  resource :session, only: [:create, :destroy, :show]
  resources :users
  resources :wordforms
  resources :mailers, only: [:create]

  get '/instructions' => 'statics#instructions'
  get '/storyinstructions' => 'statics#storyinstructions'
  get '/exclusive' => 'statics#exclusiveexplanation'
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/facebook/callback', to: 'users#create'
  get 'auth/failure', to: redirect("/")
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :username, presence: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true
  after_initialize :ensure_session_token

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def self.create_with_omniauth(auth)
    user = find_or_create_by(uid: auth['uid'], provider: auth['provider'])
    user.username = auth[:extra][:raw_info][:name]
    user.password = auth["uid"] + auth[:extra][:raw_info][:name]
    if User.exists?(user)
      user
    else
      user.save!
      user
    end
  end

  def change_username(new_username)
    self.username = new_username
    self.save!
  end

  def self.destroy_user_books(user)
    @user_books = Book.where(:user_id => user.id)
    @user_books
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user!, except: [:create, :new]

  def create
    if (params[:confirm_password] == params[:user][:password])
      @user = User.new(user_params)
      if @user.save
        login!(@user)
        render "show"
      elsif params[:user][:password].length < 6
        redirect_to new_user_path, :flash => { :error => "Password must contain at least 6 characters." }
      else
        redirect_to new_user_path, :flash => { :error => "Ensure all fields are populated." }
      end
    else
      redirect_to new_user_path, :flash => { :error => "Ensure that passwords match." }
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @book_count = Book.where(:user_id => current_user.id).count
    @user_books = Book.where(:user_id => current_user.id)
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end

  def edit
    @user = User.find(params[:id])
    render 'edit'
  end

  def update
    @user = User.find(params[:id])
    if current_user.is_password?(params[:user][:password])
      if params[:user][:username].length > 0
        current_user.change_username(params[:user][:username])
        render 'show'
      else
        redirect_to user_path(current_user), :flash => { :error => "Username field must be filled in." }
      end
    else
      redirect_to user_path(current_user), :flash => { :error => "We could not verify access to this account." }
    end
  end

  def destroy
    @user = User.find(params[:id])
    @books = User.destroy_user_books(@user)
    @books.each do |book|
      book.destroy
    end
    @user.destroy
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "patch" : "post") %>
<% message = (user.persisted? ? "Update Account" : "Sign Up") %>
<% updatemessage = (user.persisted? ? "Edit Account" : "Sign Up") %>
<% updateusername = (user.persisted? ? "Change Username" : "Username") %>
<% assign_class = (user.persisted? ? "my-account-edit-container" : "") %>

<h1 id="h1-overrides" class="home-page"><%= updatemessage %></h1>
<div class="container-fluid">
  <div class="<%= assign_class %>">
    <div class="row" id="login-row">
      <div class="col-sm-12 text-center">
        <form action="<%= action %>" method="post" class="log-in-form" autocomplete="off">
          <% if flash[:error]%>
            <p class="form-errors"><%= flash[:error] %></p>
          <% end %>
        <input
          name="_method"
          type="hidden"
          value="<%= method %>">
        <input
          name="authenticity_token"
          type="hidden"
          value="<%= form_authenticity_token %>">
          <% if current_user %>
            <p class="log-in-label">Username: <%= current_user.username %></p>
          <% end %>
        <label for="user_username" class="log-in-label"><%= updateusername %></label><br>
        <input
          id="user_username"
          name="user[username]"
          type="text"
          id="user_username" class="log-in-inputs"
          autocomplete="off"
          >
        <br>

        <label for="user_password" class="log-in-label">Password</label><br>
        <input
          id="user_password"
          name="user[password]"
          type="password"
          id="user_password" class="log-in-inputs"
          autocomplete="off"
          >
        <br>

      <% if method == "post"%>
        <label for="user_password" class="log-in-label">Confirm Password</label><br>
        <input
          id="user_password"
          name="confirm_password"
          type="password"
          id="user_password" class="log-in-inputs"
          autocomplete="off"
          >
        <br>
      <% end %>

    <input type="submit" class="log-in-inputs log-in-button" value="<%= message %>"><br>
          <%if current_user.nil? %>
            <a href="/auth/facebook">
              <button type="button" name="button" id="facebook-button">
                <i class="fa fa-facebook"></i>
                  Signup with Facebook
              </button>
            </a>
          <% end %>
          <% if current_user %>
            <%= link_to user_path(current_user.id),
              :action => :destroy,
              :method => :delete,
              :class => "remove-underline",
              data: { confirm: "Are you sure you want to delete your account?" } do %>
                <div class="log-in-inputs log-in-button delete-account">
                  Delete Account
                </div>
              <% end %>
          <% end %>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render "form", user: @user %>

app/views/users/new.html.erb
<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1 id="h1-overrides" class="home-page">My Account</h1>
<div class="container-fluid">
  <div class="my-account-edit-container user-container">
    <div class="row text-center inner-user-container">
      <div class="col-sm-12">
        <h2>Username: <%= current_user.username%></h2>
      </div>
      <div class="col-sm-12">
        <h2>You've made <%= @book_count %> books so far.</h2>
      </div>
      <% if !@user_books.nil? && @user_books.length > 0 %>
      <div class="col-sm-12">
        <h2>You're most recent book is called:<br>
          <div class="user-books-list">
            <%= link_to @user_books.last.title, book_madlibs_path(@user_books.last.id) %>
          </div>
        and was created on <%= @user_books.last.created_at.month %>/<%= @user_books.last.created_at.day %>/<%= @user_books.last.created_at.year %>.</h2>
      </div>
      <h2>Here are all the books you've made so far:</h2>
          <% @user_books.each do |book| %>
            <div class="col-sm-12 user-books-list">
              <%= link_to book.title, book_madlibs_path(book.id) %>
            </div>
          <% end %>
      <% else %>
        <h2>Write your first book today!</h2>
      <% end %>
      <div class="col-sm-12 edit-user-profile">
        <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
      </div>
    </div>
  </div>
</div>